"use client";

import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
type Row={id:string;file_name:string;score:number|null;created_at:string;assessment_type:string};
const label=(t:string)=>t==="existing"?"Assessment 1 · Hotel Existing":t==="pre-opening"?"Assessment 2 · Pre-opening Hotel":"Assessment 3 · Financial";
export default function LaporanPage(){const router=useRouter();const[rows,setRows]=useState<Row[]>([]);const[checking,setChecking]=useState(true);
useEffect(()=>{(async()=>{const{data:auth}=await supabase.auth.getSession();if(!auth.session){router.replace("/login?next=/laporan");return}const{data,error}=await supabase.from("assessment_reports").select("id,file_name,score,created_at,assessment_type").order("created_at",{ascending:false});if(error)console.error("Gagal memuat laporan:",error);setRows((data||[])as Row[]);setChecking(false)})()},[router]);
if(checking)return <main className="min-h-screen bg-[#f4f7fb] px-6 py-12 lg:pl-[280px]"><p>Memeriksa akun...</p></main>;
return <main className="min-h-screen bg-[#f4f7fb] px-6 py-12 lg:pl-[280px]"><div className="mx-auto max-w-5xl"><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#6b8a80]">CoreStay</p><h1 className="mt-3 text-4xl font-semibold">Laporan</h1><p className="mt-4 text-[#66738a]">Semua laporan assessment yang tersimpan pada akun Anda.</p>{rows.length===0?<div className="mt-8 rounded-3xl border border-[#dce4ef] bg-white p-8"><h2 className="text-xl font-semibold">Belum ada laporan</h2><p className="mt-2 text-sm text-[#66738a]">Selesaikan assessment untuk menyimpan laporan.</p></div>:<div className="mt-8 space-y-4">{rows.map(x=><div key={x.id} className="rounded-3xl border border-[#dce4ef] bg-white p-6"><p className="text-xs font-bold uppercase tracking-wider text-[#6b8a80]">{label(x.assessment_type)}</p><h2 className="mt-1 font-semibold">{x.file_name}</h2><p className="mt-1 text-sm text-[#66738a]">{new Date(x.created_at).toLocaleString("id-ID")} · Score {x.score??"-"}/100</p>{x.assessment_type==="financial"?<button onClick={async()=>{const{data:{session}}=await supabase.auth.getSession();if(!session){router.replace("/login");return}const r=await fetch("/api/assessment/financial/report/"+x.id,{headers:{Authorization:"Bearer "+session.access_token}});if(!r.ok)return;const b=await r.blob(),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="CoreStay-Financial-Assessment.pdf";a.click();URL.revokeObjectURL(u)}} className="mt-4 rounded-xl bg-[#203b68] px-5 py-3 text-sm font-bold text-white">Download PDF</button>:<p className="mt-4 text-sm text-[#66738a]">Hasil assessment tersimpan. Detail dapat dilihat pada hasil assessment.</p>}</div>)}</div>}</div></main>}
