"use client";
import Image from "next/image";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { supabase } from "@/lib/supabase";

const assessmentItems = [
  ["Assessment 1", "Hotel Existing", "/assessment/existing"],
  ["Assessment 2", "Pre-opening Hotel", "/assessment/pre-opening"],
  ["Assessment 3", "Financial Report PDF", "/assessment/financial"],
  ["Semua Assessment", "Lihat semua", "/assessment"],
] as const;
const mainItems = [["Dashboard", "/", "⌂"], ["Hasil Assessment", "/laporan", "▤"], ["Paket & Harga", "/paket-harga", "◆"]] as const;

function MenuIcon({ children }: { children: React.ReactNode }) { return <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-white/10 text-sm text-white/60 transition group-hover:bg-white/15 group-hover:text-white">{children}</span>; }
function FooterCard() { return <div className="shrink-0 border-t border-white/10 pt-3"><div className="rounded-2xl border border-white/70 bg-white/5 p-3.5 shadow-[0_10px_30px_rgba(23,50,77,.08)] backdrop-blur-md"><div className="flex items-center gap-2.5"><div className="flex h-8 w-8 items-center justify-center rounded-xl bg-[#c6a56b]/15 text-sm text-[#9a793f]">◆</div><div className="min-w-0"><p className="truncate text-[10px] font-bold uppercase tracking-[0.16em] text-white">CoreStay Advisory</p><p className="mt-0.5 text-[10px] text-white/50">Hospitality Business Advisory</p></div></div><a href="https://wa.me/6285109006363" target="_blank" rel="noopener noreferrer" className="mt-3 flex items-center justify-center rounded-xl bg-black px-3 py-2.5 text-xs font-bold text-white shadow-sm transition hover:-translate-y-0.5 hover:bg-neutral-900">Talk to Us <span className="ml-1.5">↗</span></a></div><p className="mt-2 text-center text-[9px] text-white/30">© CoreStay Advisory</p></div>; }

export default function CoreStaySidebar() {
  const pathname = usePathname();
  const [open, setOpen] = useState(false);
  const [assessmentOpen, setAssessmentOpen] = useState(true);
  const [loggedIn, setLoggedIn] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);
  const hidden = pathname.startsWith("/admin") || pathname.startsWith("/pms");
  const activeAssessment = pathname === "/assessment" || pathname.startsWith("/assessment/");
  const close = () => setOpen(false);

  useEffect(() => { if (activeAssessment) setAssessmentOpen(true); }, [activeAssessment]);
  useEffect(() => { let mounted = true; supabase.auth.getSession().then(({ data }) => { if (mounted) setLoggedIn(!!data.session); }); const { data: listener } = supabase.auth.onAuthStateChange((_event, session) => { if (mounted) setLoggedIn(!!session); }); return () => { mounted = false; listener.subscription.unsubscribe(); }; }, []);
  useEffect(() => { requestAnimationFrame(() => { const el = menuRef.current?.querySelector<HTMLElement>('[aria-current="page"]'); el?.scrollIntoView({ block: "nearest", behavior: "smooth" }); }); }, [pathname]);

  async function logout() { await supabase.auth.signOut(); setLoggedIn(false); setOpen(false); window.location.href = "/"; }

  if (hidden) return null;

  const nav = <div ref={menuRef} className="flex min-h-0 flex-1 flex-col overflow-y-auto overscroll-contain pr-1 pb-3 [scrollbar-width:thin] [scrollbar-color:rgba(23,50,77,.2)_transparent]"><p className="px-2 text-[9px] font-bold uppercase tracking-[0.25em] text-white/35">Workspace</p><nav className="mt-2 space-y-1">
    {mainItems.slice(0, 1).map(([label, href, icon]) => <Link aria-current={pathname === href ? "page" : undefined} key={label} href={href} onClick={close} className={`group flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition ${pathname === href ? "bg-white/10 text-white shadow-[0_6px_18px_rgba(23,50,77,.07)]" : "text-white/65 hover:bg-white/5 hover:text-white"}`}><MenuIcon>{icon}</MenuIcon><span>{label}</span>{pathname === href && <span className="ml-auto h-1.5 w-1.5 rounded-full bg-[#c6a56b]" />}</Link>)}
    <div className={`rounded-2xl ${activeAssessment ? "bg-white/5" : ""}`}><button type="button" onClick={() => setAssessmentOpen(v => !v)} aria-expanded={assessmentOpen} className={`group flex w-full items-center justify-between rounded-xl px-3 py-2.5 text-left text-sm font-medium transition ${activeAssessment ? "text-white" : "text-white/65 hover:bg-white/5 hover:text-white"}`}><span className="flex items-center gap-3"><MenuIcon>◎</MenuIcon>Assessment</span><span className={`text-xs text-white/40 transition-transform duration-200 ${assessmentOpen ? "rotate-90" : ""}`}>›</span></button><div className={`overflow-hidden transition-[max-height,opacity] duration-300 ${assessmentOpen ? "max-h-72 opacity-100" : "max-h-0 opacity-0"}`}><div className="ml-6 mt-0.5 space-y-0.5 border-l border-white/10 pl-2 pb-1">{assessmentItems.map(([label, desc, href]) => <Link aria-current={pathname === href ? "page" : undefined} key={label} href={href} onClick={close} className={`block rounded-lg px-3 py-2 transition ${pathname === href ? "bg-white/10 text-white shadow-sm" : "text-white/65/70 hover:bg-white/10 hover:text-white"}`}><span className="block text-xs font-medium">{label}</span><span className="mt-0.5 block text-[9px] text-white/40">{desc}</span></Link>)}</div></div></div>
    {mainItems.slice(1).map(([label, href, icon]) => <Link aria-current={pathname === href ? "page" : undefined} key={label} href={href} onClick={close} className={`group flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition ${pathname === href ? "bg-white/10 text-white shadow-[0_6px_18px_rgba(23,50,77,.07)]" : "text-white/65 hover:bg-white/5 hover:text-white"}`}><MenuIcon>{icon}</MenuIcon><span>{label}</span>{pathname === href && <span className="ml-auto h-1.5 w-1.5 rounded-full bg-[#c6a56b]" />}</Link>)}
  </nav><p className="mt-6 px-2 text-[9px] font-bold uppercase tracking-[0.25em] text-white/35">Account</p><nav className="mt-2 space-y-1">{loggedIn ? <><Link aria-current={pathname === "/profil" ? "page" : undefined} href="/profil" onClick={close} className={`group flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition ${pathname === "/profil" ? "bg-white/10 text-white" : "text-white/65 hover:bg-white/5 hover:text-white"}`}><MenuIcon>◉</MenuIcon>Profil</Link><button type="button" onClick={logout} className="group flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-medium text-white/65 transition hover:bg-white/5 hover:text-white"><MenuIcon>↪</MenuIcon>Logout</button></> : <><Link href="/login" onClick={close} className="group flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-white/65 transition hover:bg-white/5 hover:text-white"><MenuIcon>→</MenuIcon>Login</Link><Link href="/signup" onClick={close} className="group flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-white/65 transition hover:bg-white/5 hover:text-white"><MenuIcon>+</MenuIcon>Sign Up</Link></>}</nav></div>;

  return <><aside className="site-sidebar fixed inset-y-0 left-0 z-[100] hidden w-[264px] border-r border-white/10 bg-black text-white shadow-[4px_0_24px_rgba(0,0,0,.25)] lg:flex lg:flex-col"><div className="flex h-full min-h-0 flex-col px-4 py-4"><Link href="/" className="flex shrink-0 items-center rounded-2xl bg-black px-3 py-2.5 shadow-md hover:bg-neutral-900"><Image src="/logo-corestay.png" alt="CoreStay Advisory" width={180} height={70} className="h-auto w-[150px] object-contain mix-blend-screen" priority /></Link><div className="my-3 h-px bg-white/10" /><div className="flex min-h-0 flex-1 flex-col">{nav}</div><FooterCard /></div></aside><div className="site-sidebar-mobile lg:hidden"><button type="button" onClick={() => setOpen(true)} aria-label="Open menu" className="fixed left-3 top-3 z-[120] flex h-11 w-11 items-center justify-center rounded-2xl border border-white/10 bg-white text-white shadow-[0_8px_24px_rgba(23,50,77,.12)] backdrop-blur-md"><span className="flex w-5 flex-col gap-1"><i className="h-0.5 w-full bg-black" /><i className="h-0.5 w-full bg-black" /><i className="h-0.5 w-full bg-black" /></span></button><div onClick={close} className={`fixed inset-0 z-[110] bg-black/60 backdrop-blur-[3px] transition-opacity ${open ? "opacity-100" : "pointer-events-none opacity-0"}`} /><aside className={`fixed inset-y-0 left-0 z-[115] flex w-[292px] flex-col bg-white px-4 py-4 text-white shadow-2xl transition-transform duration-300 ease-out ${open ? "translate-x-0" : "-translate-x-full"}`}><div className="flex shrink-0 items-center justify-between"><Link href="/" onClick={close} className="rounded-2xl bg-black px-3 py-2 shadow-[0_8px_24px_rgba(23,50,77,.16)]"><Image src="/logo-corestay.png" alt="CoreStay Advisory" width={180} height={70} className="h-auto w-[145px] object-contain mix-blend-screen" /></Link><button type="button" onClick={close} aria-label="Close menu" className="flex h-9 w-9 items-center justify-center rounded-xl border border-white/10 bg-white text-xl text-white/60 transition hover:bg-white hover:text-white">×</button></div><div className="my-3 h-px bg-white/10" /><div className="flex min-h-0 flex-1 flex-col">{nav}</div><FooterCard /></aside></div></>;
}
