import { NextResponse } from "next/server";
import { get, del } from "@vercel/blob";
import { generateObject } from "ai";
import { createGoogleGenerativeAI } from "@ai-sdk/google";
import { extractText, getDocumentProxy } from "unpdf";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { createClient } from "@supabase/supabase-js";
import { z } from "zod";

export const runtime = "nodejs";
export const maxDuration = 300;

const FinancialAssessment = z.object({
  financialHealthScore: z.number().min(0).max(100),
  dataCompletenessScore: z.number().min(0).max(100),
  revenueHealthScore: z.number().min(0).max(100),
  profitabilityHealthScore: z.number().min(0).max(100),
  costControlScore: z.number().min(0).max(100),
  cashFlowScore: z.number().min(0).max(100),
  internalControlScore: z.number().min(0).max(100),
  revenueIntegrityScore: z.number().min(0).max(100),
  executiveSummary: z.string(),
  revenueAnalysis: z.string(),
  costAnalysis: z.string(),
  profitAnalysis: z.string(),
  comparativeAnalysis: z.string(),
  ratioAnalysis: z.string(),
  varianceAnalysis: z.string(),
  auditFindings: z.array(z.string()).max(8),
  risks: z.array(z.string()).max(8),
  recommendations: z.array(z.string()).max(8),
  actionPlan: z.array(z.string()).max(8),
  dataLimitations: z.array(z.string()).max(6),
  conclusion: z.string(),
  extractedFigures: z.array(z.object({ label: z.string(), value: z.string(), period: z.string() })).max(40),
});

function wrap(text: string, max = 92) {
  const words = text.replace(/\s+/g, " ").split(" ");
  const lines: string[] = [];
  let line = "";
  for (const w of words) {
    if ((line + " " + w).trim().length > max) {
      if (line) lines.push(line);
      line = w;
    } else {
      line = (line + " " + w).trim();
    }
  }
  if (line) lines.push(line);
  return lines;
}

async function makePdf(fileName: string, result: z.infer<typeof FinancialAssessment>) {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  let page = doc.addPage([595, 842]);
  let y = 800;

  const add = (text: string, size = 10, b = false) => {
    for (const line of wrap(text)) {
      if (y < 55) {
        page = doc.addPage([595, 842]);
        y = 800;
      }
      page.drawText(line, { x: 45, y, size, font: b ? bold : font, color: rgb(0.1, 0.14, 0.22) });
      y -= size + 6;
    }
  };

  add("CoreStay Advisory", 12, true);
  add("FINANCIAL REPORT ASSESSMENT", 18, true);
  add("Source: " + fileName, 9);
  y -= 8;
  add("Financial Health Score: " + result.financialHealthScore + "/100", 15, true);
  add("Data Completeness Score: " + result.dataCompletenessScore + "/100", 10, true);
  add("Revenue Health: " + result.revenueHealthScore + " | Profitability: " + result.profitabilityHealthScore + " | Cost Control: " + result.costControlScore);
  add("Cash Flow: " + result.cashFlowScore + " | Internal Control: " + result.internalControlScore + " | Revenue Integrity: " + result.revenueIntegrityScore);
  y -= 6;

  for (const [title, text] of [
    ["Executive Summary", result.executiveSummary], ["Revenue Analysis", result.revenueAnalysis],
    ["Cost Analysis", result.costAnalysis], ["Profit Analysis", result.profitAnalysis],
    ["Comparative Analysis", result.comparativeAnalysis], ["Ratio & Margin Analysis", result.ratioAnalysis],
    ["Variance Analysis", result.varianceAnalysis], ["Conclusion", result.conclusion],
  ] as const) {
    add(title, 13, true); add(text); y -= 6;
  }

  for (const [title, items] of [
    ["Auditor-Style Findings", result.auditFindings], ["Risks / Red Flags", result.risks],
    ["Recommendations", result.recommendations], ["Action Plan", result.actionPlan], ["Data Limitations", result.dataLimitations],
  ] as const) {
    add(title, 13, true); items.forEach((x, i) => add(i + 1 + ". " + x)); y -= 5;
  }

  add("Extracted Financial Figures", 13, true);
  result.extractedFigures.forEach((x) => add(x.label + ": " + x.value + " (" + x.period + ")"));
  add("Generated by CoreStay Financial Assessment Engine", 8);

  const bytes = await doc.save();
  return Buffer.from(bytes).toString("base64");
}

function isRetryableAiError(error: unknown) {
  const message = error instanceof Error ? error.message : String(error);
  return /high demand|overloaded|capacity|temporar|rate.?limit|429|503|service unavailable|internal server error/i.test(message);
}

export async function POST(request: Request) {
  let pdf: any = null;

  try {
    const auth = request.headers.get("authorization") || "";
    if (!auth.startsWith("Bearer ")) return NextResponse.json({ error: "Login diperlukan." }, { status: 401 });

    const supabase = createClient(
      "https://vkejwklhijophavlosze.supabase.co",
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "missing",
      { global: { headers: { Authorization: auth } } }
    );
    const { data: { user }, error: userError } = await supabase.auth.getUser();
    if (userError || !user) return NextResponse.json({ error: "Session login tidak valid." }, { status: 401 });

    const formData = await request.formData();
    const action = String(formData.get("action") || "analyze");
    const fileEntry = formData.get("file");
    const file = fileEntry instanceof File ? fileEntry : null;
    const extractedText = String(formData.get("text") || "").trim();
    const blobPath = String(formData.get("blobPath") || "").trim();
    const submittedFileName = String(formData.get("fileName") || "Financial-Report.pdf");

    if (action === "analyze") {
      if (!blobPath && !extractedText) return NextResponse.json({ error: "File laporan belum tersedia." }, { status: 400 });
      if (blobPath && !blobPath.startsWith("financial-reports/")) return NextResponse.json({ error: "Lokasi file tidak valid." }, { status: 400 });
      if (extractedText && extractedText.length < 20) return NextResponse.json({ error: "Teks laporan terlalu pendek untuk dianalisa." }, { status: 422 });
    } else if (!(file instanceof File)) {
      return NextResponse.json({ error: "File PDF belum dipilih." }, { status: 400 });
    }
    if (action !== "analyze" && file instanceof File && file.type !== "application/pdf" && !file.name.toLowerCase().endsWith(".pdf")) {
      return NextResponse.json({ error: "File harus berformat PDF." }, { status: 400 });
    }
    if (action !== "analyze" && file instanceof File && file.size > 4 * 1024 * 1024) {
      return NextResponse.json({ error: "Ukuran PDF maksimal 4 MB." }, { status: 400 });
    }
    if (action === "analyze" && !process.env.GEMINI_API_KEY) return NextResponse.json({ error: "Gemini API belum aktif pada deployment ini." }, { status: 503 });

    let text = extractedText;
    if (blobPath) {
      const blobResult = await get(blobPath, { access: "private" });
      if (!blobResult || blobResult.statusCode !== 200 || !blobResult.stream) {
        return NextResponse.json({ error: "File laporan tidak ditemukan atau tidak dapat dibaca." }, { status: 404 });
      }
      const buffer = await new Response(blobResult.stream).arrayBuffer();
      pdf = await getDocumentProxy(new Uint8Array(buffer));
      const parsed = await extractText(pdf, { mergePages: true });
      text = parsed.text.trim();
    } else if (action !== "analyze") {
      const buffer = await (file as File).arrayBuffer();
      pdf = await getDocumentProxy(new Uint8Array(buffer));
      const parsed = await extractText(pdf, { mergePages: true });
      text = parsed.text.trim();
    }

    if (!text) return NextResponse.json({ error: "PDF tidak memiliki teks yang dapat dibaca. OCR perlu ditambahkan untuk PDF scan." }, { status: 422 });
    if (action === "extract") return NextResponse.json({ success: true, fileName: (file as File).name, text });

    const google = createGoogleGenerativeAI({ apiKey: process.env.GEMINI_API_KEY });
    const models = ["gemini-3.8-flash", "gemini-3.7-flash", "gemini-3.5-flash-lite"];
    const system = "Anda adalah Senior Hotel Financial Auditor & Hospitality Finance Consultant untuk CoreStay. Anda wajib menganalisis FILE LAPORAN KEUANGAN YANG BENAR-BENAR DIUPLOAD pengguna, bukan membuat ringkasan generik. FILE PROCESSING RULE: file upload adalah sumber utama analisis. Jika file gagal dibaca, kosong, corrupt, tidak memiliki data yang dapat diekstrak, atau data penting tidak dapat diproses, JANGAN membuat Financial Audit Report; keluarkan dataLimitations yang menyatakan FILE/DATA PROCESSING ERROR dan jelaskan bagian yang gagal dibaca serta tindakan yang diperlukan. Jangan mengarang angka, transaksi, periode, mata uang, benchmark, budget, forecast, target, rasio, atau tren. Jika data tidak tersedia, tulis Tidak tersedia – indikator tidak dapat dihitung secara valid. Baca seluruh isi yang berhasil diekstrak dan analisis seluruh bagian yang relevan. Lakukan DATA EXTRACTION -> VALIDATION -> CALCULATION -> COMPARISON -> FINDING -> FINANCIAL IMPACT -> RISK -> ACTION. Periksa subtotal, total, duplikasi, missing data, inkonsistensi, perubahan ekstrem, dan angka negatif yang tidak wajar; tandai DATA INTEGRITY ISSUE. Hitung KPI hanya jika numerator dan denominator valid. Pisahkan FACT, CALCULATION, FINDING, INDICATION, dan ASSUMPTION. Score 0-100 harus dapat dijelaskan berdasarkan data yang tersedia; jika data tidak lengkap, turunkan dataCompletenessScore dan jelaskan keterbatasannya. Jangan membuat benchmark industri sendiri. Jangan menyatakan fraud/kecurangan sebagai fakta atau memberikan opini audit independen tanpa bukti memadai; gunakan 'indikasi yang perlu diperiksa lebih lanjut'. Gunakan prinsip evidence-based, materiality praktis, consistency, variance analysis, risk assessment, dan source traceability. Untuk temuan material, sebutkan sumber yang dapat ditelusuri dari file, minimal nama file, periode, sheet/bagian/akun bila tersedia. Prioritaskan MONEY LOST, MONEY AT RISK, MONEY THAT CAN BE SAVED, MONEY THAT CAN BE RECOVERED, dan MONEY THAT CAN BE GENERATED.";
    const prompt = "Lakukan FINANCIAL REPORT AUDIT terhadap file berikut. Nama file: " + (file?.name || submittedFileName) + "\n\n" + text + "\n\nWAJIB: validasi file dan data terlebih dahulu; identifikasi nama laporan, periode, mata uang, Actual, Budget, Forecast, Previous Period, MTD/YTD, room nights, revenue, expense, profit, cash flow, dan data yang hilang; analisis revenue, room revenue, occupancy, ADR, RevPAR, F&B, other operating revenue, departmental expenses, undistributed expenses, payroll, utilities, S&M, A&G, R&M, GOP, GOP margin, EBITDA/operating profit, net profit/loss, cash flow, budget vs actual, forecast vs actual, cost efficiency, internal control, revenue leakage, cost leakage, dan anomali; hitung KPI dan rasio hanya jika data valid; analisis hubungan KPI; cari red flags dan indikasi leakage tanpa menyatakan fraud sebagai fakta; gunakan DATA -> CALCULATION -> FINDING -> FINANCIAL IMPACT -> RISK -> ACTION dan source traceability untuk temuan material. Output wajib mencakup Overall Financial Health Score, Data Completeness Score, enam component scores, Executive Summary maksimal 10 poin, Financial Scorecard, Top 5 Financial Findings, Financial Red Flags, Potential Saving/Recovery, Management Action Plan, 30-Day Action Plan, 90-Day Action Plan, dan Management Conclusion. Karena schema menyimpan beberapa bagian sebagai string, tuliskan Financial Scorecard di comparativeAnalysis, KPI relationships di comparativeAnalysis, variance di varianceAnalysis, Top 5 di auditFindings, Red Flags di risks, Potential Saving/Recovery di recommendations, dan Management Action Plan + 30/90 day actions di actionPlan. Jangan memaksakan lima temuan; maksimal 5 yang didukung data. Jika data tidak cukup, tulis 'Tidak tersedia – indikator tidak dapat dihitung secara valid.' Jika target saving tidak tersedia, jangan mengarang target. Jangan membuat tren palsu bila hanya satu periode. Gunakan bahasa Indonesia profesional, ringkas, tajam, terukur. extractedFigures WAJIB mengupayakan enam baris Financial Scorecard dengan label persis: Revenue, GOP, GOP Margin, Operating Cost, Net Profit, Cash Flow. Untuk setiap indikator, gunakan angka asli dari file jika tersedia, sertakan periodenya, dan jangan mengarang; bila tidak tersedia gunakan value 'Tidak tersedia – indikator tidak dapat dihitung secara valid.'. Cash Flow wajib dicari secara eksplisit dari laporan (cash flow statement, operating cash flow, net cash flow, atau istilah setara) dan tetap dimasukkan ke extractedFigures bila tersedia.";

    let result: Awaited<ReturnType<typeof generateObject<typeof FinancialAssessment>>> | null = null;
    let lastAiError: unknown = null;
    for (const modelId of models) {
      try {
        result = await generateObject({ model: google(modelId), schema: FinancialAssessment, system, prompt });
        break;
      } catch (error) {
        lastAiError = error;
        console.error("Financial assessment model failed:", modelId, error);
        if (!isRetryableAiError(error)) throw error;
      }
    }
    if (!result) return NextResponse.json({ error: "Layanan AI sedang penuh. CoreStay sudah mencoba beberapa model Gemini. Silakan ulangi beberapa saat lagi." }, { status: 503 });

    const pdfBase64 = await makePdf(action === "analyze" ? submittedFileName : (file as File).name, result.object);
    const { data: saved, error: saveError } = await supabase.from("assessment_reports").insert({
      user_id: user.id, assessment_type: "financial", file_name: action === "analyze" ? submittedFileName : (file as File).name,
      score: Math.round(result.object.financialHealthScore), report_json: result.object, pdf_base64: pdfBase64,
    }).select("id,created_at").single();

    if (saveError) return NextResponse.json({ error: "Hasil analisa berhasil dibuat tetapi gagal disimpan. Jalankan migration Supabase assessment_reports terlebih dahulu." }, { status: 500 });
    if (blobPath) {
      try { await del(blobPath, { token: process.env.BLOB_READ_WRITE_TOKEN }); } catch (cleanupError) { console.error("Financial source cleanup failed:", cleanupError); }
    }
    return NextResponse.json({ success: true, reportId: saved.id, createdAt: saved.created_at, fileName: file?.name || submittedFileName, result: result.object });
  } catch (error) {
    console.error(error);
    return NextResponse.json({ error: error instanceof Error ? error.message : "Server gagal memproses PDF." }, { status: 500 });
  } finally {
    if (pdf) { try { pdf.cleanup(); } catch {} }
  }
}
